/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vue;

import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.border.Border;

/**
 *
 * @author Niakulu
 */
public class fenProduits extends javax.swing.JFrame {

    private ComboBoxModel<String> SousCatAppareilPhoto;
    private ComboBoxModel<String> SousCatCasqueAudio;
    private Border redline;
    java.applet.AudioClip son1, son2;
    java.net.URL url1 = fenProduits.class.getResource("/son/726.wav");
    java.net.URL url2 = fenProduits.class.getResource("/son/727.wav");

   
    /**
     * Creates new form fenProduits
     */
    public fenProduits() {
        String[] lesAppareilsPhoto = {"Reflex","Analogique", "Numerique"};
        SousCatAppareilPhoto = new DefaultComboBoxModel(lesAppareilsPhoto );
        
        String[] lesCasquesAudio = {"Casque isolant","Casque cher", "Casque nul"};
        SousCatCasqueAudio = new DefaultComboBoxModel(lesCasquesAudio);

        son1 = java.applet.Applet.newAudioClip(url1);
        son2 = java.applet.Applet.newAudioClip(url2);
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panCarac = new javax.swing.JPanel();
        libLib = new javax.swing.JLabel();
        textLib = new javax.swing.JTextField();
        libCat = new javax.swing.JLabel();
        cbCat = new javax.swing.JComboBox<>();
        libSousCat = new javax.swing.JLabel();
        libSousCat.setVisible(false);
        cbSousCat = new javax.swing.JComboBox<>();
        cbSousCat.setVisible(false);
        libPrix = new javax.swing.JLabel();
        textPrix = new javax.swing.JTextField();
        btSuppr = new javax.swing.JButton();
        btModif = new javax.swing.JButton();
        btAjout = new javax.swing.JButton();
        btSon1 = new javax.swing.JButton();
        btSon2 = new javax.swing.JButton();
        mbMenu = new javax.swing.JMenuBar();
        mFichier = new javax.swing.JMenu();
        miExport = new javax.swing.JMenuItem();
        miQuitter = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        miAide = new javax.swing.JMenuItem();
        miVersion = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panCarac.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Caractéristiques produits", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 2, 10))); // NOI18N

        libLib.setText("Libellé");

        textLib.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textLibActionPerformed(evt);
            }
        });

        libCat.setText("Catégorie");

        cbCat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Disque Dur", "Souris", "LecteurDVD", "Casque Audio", "Appareil Photo" }));
        cbCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCatActionPerformed(evt);
            }
        });

        libSousCat.setText("Sous-catégorie");

        cbSousCat.setModel(SousCatAppareilPhoto);
        cbSousCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSousCatActionPerformed(evt);
            }
        });

        libPrix.setText("Prix");

        btSuppr.setText("Supprimer");
        btSuppr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btSupprMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btSupprMouseExited(evt);
            }
        });
        btSuppr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSupprActionPerformed(evt);
            }
        });

        btModif.setText("Modifier");

        btAjout.setText("Ajouter");
        btAjout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAjoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panCaracLayout = new javax.swing.GroupLayout(panCarac);
        panCarac.setLayout(panCaracLayout);
        panCaracLayout.setHorizontalGroup(
            panCaracLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panCaracLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panCaracLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panCaracLayout.createSequentialGroup()
                        .addComponent(btSuppr)
                        .addGap(62, 62, 62)
                        .addComponent(btModif)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btAjout))
                    .addGroup(panCaracLayout.createSequentialGroup()
                        .addGroup(panCaracLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panCaracLayout.createSequentialGroup()
                                .addComponent(libLib)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(textLib, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panCaracLayout.createSequentialGroup()
                                .addComponent(libCat)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbCat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(libSousCat)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbSousCat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panCaracLayout.createSequentialGroup()
                                .addComponent(libPrix)
                                .addGap(26, 26, 26)
                                .addComponent(textPrix, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 33, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panCaracLayout.setVerticalGroup(
            panCaracLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panCaracLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panCaracLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(libLib)
                    .addComponent(textLib, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panCaracLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(libCat)
                    .addComponent(cbCat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(libSousCat)
                    .addComponent(cbSousCat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panCaracLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(libPrix)
                    .addComponent(textPrix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(panCaracLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSuppr)
                    .addComponent(btModif)
                    .addComponent(btAjout)))
        );

        btSon1.setText("Son 1 ");
        btSon1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSon1ActionPerformed(evt);
            }
        });

        btSon2.setText("Son 2 ");
        btSon2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSon2ActionPerformed(evt);
            }
        });

        mFichier.setText("Fichier");

        miExport.setText("Export Excel");
        mFichier.add(miExport);

        miQuitter.setText("Quitter");
        miQuitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miQuitterActionPerformed(evt);
            }
        });
        mFichier.add(miQuitter);

        mbMenu.add(mFichier);

        jMenu2.setText("A propos");

        miAide.setText("Aide");
        miAide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAideActionPerformed(evt);
            }
        });
        jMenu2.add(miAide);

        miVersion.setText("Version");
        miVersion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miVersionActionPerformed(evt);
            }
        });
        jMenu2.add(miVersion);

        mbMenu.add(jMenu2);

        setJMenuBar(mbMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panCarac, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(btSon1)
                .addGap(62, 62, 62)
                .addComponent(btSon2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panCarac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSon1)
                    .addComponent(btSon2))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textLibActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textLibActionPerformed
        
    }//GEN-LAST:event_textLibActionPerformed
//Gestion des combobox
    private void cbCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCatActionPerformed
        if (cbCat.getSelectedItem().equals("Disque Dur")){
            cbSousCat.setVisible(false);
            libSousCat.setVisible(false);
        }
        if (cbCat.getSelectedItem().equals("Souris")){
            cbSousCat.setVisible(false);
            libSousCat.setVisible(false);
        }
        if (cbCat.getSelectedItem().equals("LecteurDVD")){
            cbSousCat.setVisible(false);
            libSousCat.setVisible(false);
        }
        if (cbCat.getSelectedItem().equals("Casque Audio")){
            cbSousCat.setVisible(true);
            libSousCat.setVisible(true);
            cbSousCat.setModel( SousCatCasqueAudio );
        }
        if (cbCat.getSelectedItem().equals("Appareil Photo"))
        {
            cbSousCat.setVisible(true);
            libSousCat.setVisible(true);
            cbSousCat.setModel( SousCatAppareilPhoto );
        }
    }//GEN-LAST:event_cbCatActionPerformed

    private void cbSousCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSousCatActionPerformed

    }//GEN-LAST:event_cbSousCatActionPerformed
//Bouton supprimer : clic
    private void btSupprActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSupprActionPerformed
        textLib.setText("");
        textPrix.setText("");
        cbCat.setSelectedIndex(0);
        cbSousCat.setVisible(false);
        libSousCat.setVisible(false);
    }//GEN-LAST:event_btSupprActionPerformed
//Sous-menu Quitter
    private void miQuitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miQuitterActionPerformed
        int input = JOptionPane.showConfirmDialog(this,"Quitter l'application ?","", JOptionPane.OK_CANCEL_OPTION, JOptionPane.INFORMATION_MESSAGE);
        if (input==JOptionPane.OK_OPTION){
            System.out.println("Application Fermée");
            this.dispose();
            System.exit(0); 
         }   
         else if (input==JOptionPane.CANCEL_OPTION){
             this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
         }         
    }//GEN-LAST:event_miQuitterActionPerformed
//Bouton Supprimer : Hover in
    private void btSupprMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btSupprMouseEntered
        redline = BorderFactory.createLineBorder(Color.red, 3);
        btSuppr.setBorder(redline);
    }//GEN-LAST:event_btSupprMouseEntered
//Bouton Supprimer : Hover out
    private void btSupprMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btSupprMouseExited
        btSuppr.setBorder(BorderFactory.createEmptyBorder(4, 4, 4, 4));      
    }//GEN-LAST:event_btSupprMouseExited
//Sous-menu Version
    private void miVersionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miVersionActionPerformed
    JOptionPane.showMessageDialog(this, "Gestion de produits version 1.0", "Autrice: Béatrice Rollet",
    JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_miVersionActionPerformed
//Bouton Ajouter : clic
    private void btAjoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAjoutActionPerformed
            String Lib;
            String C = "";
            String SC = " Pas de sous catégorie";
            String Px;
        
        if (cbCat.getSelectedIndex()==0) {
            C=" Disque Dur";
        }
        if (cbCat.getSelectedIndex()==1) {
            C=" Souris";
        }
        if (cbCat.getSelectedIndex()==2) {
            C=" Lecteur DVD";
        }
        if (cbCat.getSelectedIndex()==3) {
            C=" Casque Audio";
            if (cbSousCat.getSelectedIndex()==0) SC = " Isolant";
            if (cbSousCat.getSelectedIndex()==1) SC = " Cher";
            if (cbSousCat.getSelectedIndex()==2) SC = " Nul";
        }
        if (cbCat.getSelectedIndex()==4){
            C=" Appareil Photo";
            if (cbSousCat.getSelectedIndex()==0) SC = " Reflex";
            if (cbSousCat.getSelectedIndex()==1) SC = " Analogique";
            if (cbSousCat.getSelectedIndex()==2) SC = " Numérique";
        }
        Lib=textLib.getText();
        Px = textPrix.getText();
        
        String regex = "[0-9]*";
        if (Lib.equals("")){ //libellé vide
            JOptionPane.showMessageDialog(this, "Le libellé est vide", "Erreur de saisie", JOptionPane.INFORMATION_MESSAGE);
        }
        else if( !Px.matches(regex)||Px.equals ("")){ // si prix vide, non numérique 
            JOptionPane.showMessageDialog(this, "Certains champs sont vides ou erronés", "Erreur de saisie", JOptionPane.INFORMATION_MESSAGE);
        }
        else{
            JOptionPane.showMessageDialog(this,"Vous avez ajouté le produit suivant:\n Libellé: " + Lib + "\nCatégorie: " + C + "\nSous-catégorie: " + SC + "\nPrix: "+ Px, "Produit ajouté" ,JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btAjoutActionPerformed
//Bouton Aide
    private void miAideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAideActionPerformed
        JOptionPane.showInputDialog(this, "Quelle est votre question ?", "Aide", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_miAideActionPerformed
//Bouton son1
    private void btSon1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSon1ActionPerformed
       son1.play();
    }//GEN-LAST:event_btSon1ActionPerformed
//Bouton son2
    private void btSon2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSon2ActionPerformed
        son2.play();
    }//GEN-LAST:event_btSon2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fenProduits.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fenProduits.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fenProduits.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fenProduits.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fenProduits().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAjout;
    private javax.swing.JButton btModif;
    private javax.swing.JButton btSon1;
    private javax.swing.JButton btSon2;
    private javax.swing.JButton btSuppr;
    private javax.swing.JComboBox<String> cbCat;
    private javax.swing.JComboBox<String> cbSousCat;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JLabel libCat;
    private javax.swing.JLabel libLib;
    private javax.swing.JLabel libPrix;
    private javax.swing.JLabel libSousCat;
    private javax.swing.JMenu mFichier;
    private javax.swing.JMenuBar mbMenu;
    private javax.swing.JMenuItem miAide;
    private javax.swing.JMenuItem miExport;
    private javax.swing.JMenuItem miQuitter;
    private javax.swing.JMenuItem miVersion;
    private javax.swing.JPanel panCarac;
    private javax.swing.JTextField textLib;
    private javax.swing.JTextField textPrix;
    // End of variables declaration//GEN-END:variables
}
